---
abstract: GDS2 stream module
author: [SCHUMACK Ken Schumack]
build_requires: {}
dynamic_config: 0
name: GDS2
version: 3.33
resources:
  license: http://opensource.org/licenses/artistic-license-2.0
  homepage: https://metacpan.org/module/GDS2
  repository: https://github.com/Coolwater357/GDS2
requires:
  perl: '5.008001'
  Config: 0
  IO::File: 0
  Fcntl: 0
configure_requires:
  ExtUtils::MakeMaker: 6.3
distribution_type: module
provides:
  GDS2:
    file: lib/GDS2.pm
    version: '3.33'

