---
build_requires: {}
dynamic_config: 0
name: GDS2
version: 3.32
author: [SCHUMACK Ken Schumack]
abstract: GDS2 stream module
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license-1.0
  homepage: https://metacpan.org/module/GDS2
requires:
  perl: 5.008001
configure_requires:
  ExtUtils::MakeMaker: 6.3
distribution_type: module
provides:
  GDS2:
    file: lib/GDS2.pm
    version: 3.32

